repos:
  #- repo: https://github.com/pre-commit/pre-commit-hooks
  #  rev: v4.0.1
  #  hooks:
  #    - id: trailing-whitespace
  #    - id: end-of-file-fixer
  #    - id: check-added-large-files

  #- repo: https://github.com/psf/black
  #  rev: 22.3.0
  #  hooks:
  #    - id: black
  #      args: ["--check"]

  #- repo: https://github.com/pycqa/flake8
  #  rev: 7.1.1
  #  hooks:
  #    - id: flake8

  # Custom hook to run unit tests
  - repo: local
    hooks:
      - id: run-critical-tests
        name: Run Critical Pytest Tests
        entry: poetry run pytest -m critical
        language: system
        pass_filenames: false
